
name: docker-build
on:
  push:
    branches: [ "docker", "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Docker meta
      #   id: meta
      #   uses: docker/meta-action@v4
      #   with:
      #     images: |
      #       devcose/ai-helper
      #     tags: |
      #       type=schedule
      #       type=semver,patter={{major}}

      - name: Build Image
        uses: docker/setup-buildx-action@v1
      - name: Build the Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: devcose/ai-helper:latest
          context: .
          cache-from: type=gha
          cache-to: type=gha,mox=max

